### ISSUE TITLE
Call to undefined method Intervention\Image\Image::make()

### ISSUE THREAD

**Issue by murrion** [freekmurze/browsershot#5]
Hi, I am trying out the browsershot repository in a new project.

After a fresh clone of the repository and using the sample provided in the Readme file, I get the following error:

PHP Fatal error:  Call to undefined method Intervention\Image\Image::make() in /var/www/application/vendor/spatie/browsershot/src/Spatie/Browsershot/Browsershot.php on line 163

Can you recommend a solution?

Thank you.

**Comment by freekmurze** [comment]
Hi,

thanks for bringing this problem to my attention.

I fixed this error and tagged version 1.1.0 with the solution.

**Comment by murrion** [comment]
Perfect. Working well, thank you.
