### ISSUE TITLE
Is it possible to set the height to 100%

### ISSUE THREAD

**Issue by kylenoland** [freekmurze/browsershot#8]
I'm wondering what it would take to add the ability to take full page screenshots without knowing the height of the rendered page?

**Comment by freekmurze** [comment]
I just released version 1.2.0 that is capable of rendering the entire webpage. Just use ```setHeightToRenderWholePage()```

**Comment by kylenoland** [comment]
Using the new setHeightToRenderWholePage() method throws the following exception:

[ErrorException]
imagecreatetruecolor(): Invalid image dimensions

**Comment by freekmurze** [comment]
Which site are you trying to render?

**Comment by kylenoland** [comment]
http://nolandlabs <http://nolandlabs/>.com

Thanks,

Kyle Noland
www.kylenoland.com <http://www.kylenoland.com/>
(214) 405-1606

**Comment by kylenoland** [comment]
Also, the setWidth() method does not appear to be respected any longer when using the new setHeightToRenderWholePage() method. No matter what I set the width to, it comes out as 400.

Thanks,

Kyle Noland
www.kylenoland.com <http://www.kylenoland.com/>
(214) 405-1606

**Comment by freekmurze** [comment]
Version 1.2.1 fixes the `imagecreatetrucolor`-error. 

These renders are now working:
```php
(new  Spatie\Browsershot\Browsershot())->setURL('http://arstechnica.com')->setWidth('1024')->setHeight('768')->save(storage_path('browsershot' . date('Ymd-his') .'.jpg'));

(new  Spatie\Browsershot\Browsershot())->setURL('http://arstechnica.com')->setWidth('1024')->setHeightToRenderWholePage()->save(storage_path('browsershot' . date('Ymd-his') .'.jpg'));

```
I tried rendering your site, but rendering that one still gives some rendering error. I assume the underlying ghostscript binary is causing the error. Unfortunately I don't see a way to fix that. If you have suggestions, I'm glad to hear them.

**Comment by rbhirve** [comment]
@freekmurze Does `setHeightToRenderWholePage()` method exists in version 2.0.3?

**Comment by freekmurze** [comment]
Unfortunately not. I'm hoping Chrome will add support for this behaviour in future versions of headless Chrome.

**Comment by rbhirve** [comment]
@freekmurze Okay, Is there any way to take a full screenshot of the webpage?

**Comment by freekmurze** [comment]
Not with headless Chrome atm, you can do it manually with a Chrome dev tools or a Chrome plugin.

Google a bit around to find exact instructions.
